test_prompts = [
    # Creativity and Writing
    "Write a complete novella-length short story (aim for 8,000+ words) about a generation ship's AI that has been alone for 400 years after the human passengers went into permanent cryosleep. Include the AI's evolving philosophy across centuries, at least five distinct 'eras' of its inner life, encounters with deep-space phenomena, its relationship with the sleeping humans it tends to, invented rituals it develops, and a morally ambiguous ending. Use rich sensory language, interior monologue, and flashbacks to the launch.",
    "Write a comprehensive 5,000+ word craft essay on how to write literary fiction, covering: voice, point of view (first/second/third limited/omniscient with examples of each), scene vs. summary, dialogue mechanics, subtext, image patterning, structure (Freytag, Fichtean, kishōtenketsu, in medias res, frame narratives), revision strategies, and common failure modes. For each topic, include illustrative passages you write yourself, then analyze what each technique accomplishes.",
    "Write the complete first act of a stage play (minimum 40 pages of dialogue and stage directions) about three estranged siblings returning to their childhood home to settle their late mother's estate, only to discover she left behind a series of letters revealing a decades-long secret. Include full character descriptions, set design notes, and at least six scenes with distinct dramatic beats.",
    "Compose 25 original poems on the theme of 'thresholds,' each in a different traditional form: sonnet (Shakespearean), sonnet (Petrarchan), villanelle, sestina, pantoum, ghazal, haiku sequence (10 linked), tanka sequence (10 linked), terza rima, ottava rima, rondeau, triolet, ballade, blank verse monologue, heroic couplets, Spenserian stanza, ode (Pindaric), ode (Horatian), elegy, aubade, eclogue, prose poem, found poem, erasure, and free verse. Before each poem, write a 100-word note on the form's history and constraints.",
    "Draft a complete brand identity and launch document for a fictional company called 'Lumen & Hollow' that sells handmade wooden furniture. Include: founding story (1,000 words), brand manifesto, voice and tone guide with do/don't examples, twelve sample social media posts across platforms, full website copy (homepage, about, three product pages, FAQ, contact), three blog posts (1,500 words each), email welcome sequence (5 emails), packaging copy, and press release for the launch.",
    
    # Logic and Reasoning
    "Provide an exhaustive analysis of the Monty Hall problem. Cover: the original formulation, the intuitive 'wrong' answer and why it's seductive, the correct probabilistic reasoning shown three different ways (enumeration, conditional probability with Bayes, simulation logic), historical reception including the Marilyn vos Savant controversy with specific letters from mathematicians, variations (100 doors, host doesn't know, host is adversarial, two contestants), philosophical implications for epistemology, connections to the Sleeping Beauty problem and the Two Envelopes paradox, and a final pedagogical guide on how to teach it to skeptics.",
    "Walk through, in maximum detail, fifteen famous logical paradoxes (Liar, Russell's, Sorites, Ship of Theseus, Zeno's Achilles and Arrow, Newcomb's, Grandfather, Bootstrap, Berry's, Curry's, Grelling–Nelson, Unexpected Hanging, Gödel's incompleteness as paradox, and Banach–Tarski). For each: history, precise formulation, attempted resolutions across multiple philosophical schools, your assessment of the strongest resolution and why, and implications for logic, math, or metaphysics.",
    "A complex murder mystery: Six suspects, twelve clues, three rooms, and two timelines. Construct the entire mystery from scratch—give each suspect a full biography, motive, alibi, and relationship to the victim and to each other. Then walk a detective through solving it step by step, showing the reasoning chain, every red herring considered and eliminated, every Bayesian update, and the final reconstruction of events. End with a 'how the detective explains it to the suspects in the drawing room' monologue.",
    "Generate 50 highly unconventional but genuinely practical uses for each of the following ordinary objects: a metal paperclip, a rubber band, a brick, a tennis ball, a wire coat hanger, and a dryer sheet. For each use, explain the underlying physical or chemical principle that makes it work, and rate it on a 1–5 scale for practicality, originality, and safety with justification.",
    "Construct a complete decision-theoretic analysis of the question 'Should I go to graduate school?' Build out the full decision tree with at least four levels of branching, assign probability estimates to each node with reasoning, compute expected utilities under three different utility functions (income-maximizing, meaning-maximizing, optionality-maximizing), perform sensitivity analysis on the key parameters, discuss how the answer differs across fields (humanities, STEM, professional), and address objections from behavioral economics about why this kind of analysis often misleads.",
    
    # Coding and Technical
    "Write a complete, production-quality Python implementation of a small toy language interpreter (call it 'Tinyscript'). Include: lexer with full token definitions, recursive descent parser producing an AST, tree-walking interpreter, support for integers, floats, strings, booleans, variables, if/else, while loops, functions with closures, first-class functions, lists, dicts, and a small standard library. Include 30+ unit tests, error handling with helpful messages, a REPL, and 2,000+ words of accompanying documentation explaining each component and the design decisions.",
    "Write an exhaustive guide to concurrency in modern systems, covering: processes vs threads vs fibers vs coroutines vs goroutines, the memory hierarchy and cache coherence, atomics and memory ordering (sequential consistency, acquire-release, relaxed) with C++/Rust code examples, locks (mutex, rwlock, spinlock, ticket lock), lock-free data structures (Treiber stack, Michael-Scott queue) with full implementations, the actor model, CSP, software transactional memory, async/await internals (state machine transformation), event loops, common bugs (data races, deadlocks, livelocks, ABA, false sharing) with diagnostic strategies, and a comparison of Go, Rust, Erlang, and Java approaches. Aim for 8,000+ words with code.",
    "Implement a complete miniature relational database in Python from scratch (no external libraries beyond the standard library). Include: a B+ tree index with insert/delete/range query, a heap file storage engine, a buffer pool with LRU eviction, a SQL parser supporting SELECT/INSERT/UPDATE/DELETE/CREATE TABLE/JOIN, a query planner that chooses between index and sequential scan, a basic transaction manager with two-phase locking, write-ahead logging with crash recovery, and a CLI. Include thorough comments and a 3,000+ word architectural overview.",
    "Write a complete tutorial on training a small transformer language model from scratch, suitable for someone who has used PyTorch but never trained an LM. Cover: tokenization (BPE from scratch with code), the data pipeline (streaming, packing, masking), the architecture (multi-head attention with derivation, RMSNorm, SwiGLU, RoPE with mathematical motivation), training loop (mixed precision, gradient accumulation, learning rate schedules, gradient clipping), distributed training options (DDP, FSDP, tensor parallelism, pipeline parallelism with diagrams), evaluation (perplexity, downstream tasks), debugging methodology (loss spikes, NaN diagnosis, gradient flow inspection), and inference optimizations (KV cache, speculative decoding). Include working code throughout.",
    "Pick fifteen classic algorithms and data structures (Dijkstra, A*, Floyd-Warshall, Union-Find with path compression, Fenwick tree, segment tree with lazy propagation, suffix array with LCP, KMP, Aho-Corasick, treap, skip list, persistent segment tree, link-cut tree, max-flow with Dinic's, bipartite matching with Hopcroft-Karp). For each: motivating problem, full implementation in C++ or Python with comments, complexity analysis with proof sketches, common pitfalls, and three example problems where it's the right tool with full solutions.",
    
    # Factual and Educational
    "Write a comprehensive 10,000-word history of the French Revolution from the financial crisis of the 1770s through the rise of Napoleon. Cover: structural causes (fiscal, agrarian, intellectual), the Estates-General, the storming of the Bastille, the Great Fear, the women's march on Versailles, the Civil Constitution of the Clergy, the flight to Varennes, the war with Austria, the September Massacres, the Convention, the trial and execution of Louis XVI, the Terror with biographical sketches of Robespierre/Saint-Just/Danton, Thermidor, the Directory, and the 18 Brumaire. Embed primary source quotations, address competing historiographical traditions (Marxist, revisionist, post-revisionist), and end with the Revolution's contested legacy.",
    "Provide a complete tour of cell biology suitable for a motivated undergraduate. Cover: cell theory and its history, prokaryote vs. eukaryote architecture, every major organelle in detail (nucleus, ER rough and smooth, Golgi, mitochondria with the endosymbiotic hypothesis evidence, chloroplasts, lysosomes, peroxisomes, cytoskeleton with all three filament types), the plasma membrane and transport (passive, facilitated, active, vesicular), the cell cycle with checkpoint biology, mitosis and meiosis with detailed phase comparison, signaling pathways (GPCR, RTK, JAK-STAT, Wnt, Notch, Hedgehog), apoptosis vs. necrosis vs. ferroptosis, and how cancer dysregulates each system. 8,000+ words.",
    "Write an in-depth exploration of the Fermi Paradox. Begin with Fermi's original lunchtime question and Hart's 1975 formalization. Then walk through twenty proposed solutions in detail: the Rare Earth hypothesis, the Great Filter (early vs. late), the Zoo hypothesis, the Dark Forest, the Berserker hypothesis, the simulation hypothesis as resolution, the transcension hypothesis, the firstborn hypothesis, communication mismatch (timescale, frequency, modality), self-destruction filters, the planetarium hypothesis, postbiological evolution, the aestivation hypothesis, the percolation theory of colonization, sublight expansion economics, and several more. For each: the steelmanned argument, empirical constraints, and how it could in principle be tested.",
    "Write a complete, accessible explanation of general relativity. Begin with the equivalence principle and Einstein's elevator thought experiment, build up tensor calculus from scratch (vectors, dual vectors, tensors, the metric, covariant derivative, Christoffel symbols, Riemann curvature, Ricci tensor, Ricci scalar), derive the Einstein field equations, then solve for: the Schwarzschild metric (with derivation), perihelion precession of Mercury, gravitational lensing, gravitational time dilation, the Kerr metric (qualitatively), gravitational waves (linearized theory), and FLRW cosmology. Include diagrams described in detail and worked numerical examples. 10,000+ words.",
    "Write an exhaustive history of the Australian capital question, from federation in 1901 through the design competition for Canberra, Walter Burley Griffin's plan, the construction phases, the move of government in 1927, and Canberra's evolution as a planned city. Embed this in the broader history of capital city selection worldwide, comparing with Brasília, Washington D.C., Ottawa, Abuja, Astana, and Naypyidaw. Conclude with a discussion of what makes a planned capital succeed or fail.",
    
    # Formatting and Constraints
    "Generate a richly detailed JSON document representing a fictional library's complete catalog: 30 books across 6 genres, each with title, author (with full nested author objects including birth/death years, nationality, bibliography), publication year, ISBN, publisher, page count, language, original language, translator (where applicable), genres (array), tags (array), summary (100+ words), 3 fictional reader reviews each (with reviewer name, rating, date, full review text), checkout history (10 entries each), and a 'related works' array. Then describe the schema in a separate section.",
    "Produce a single comprehensive Markdown document comparing 30 programming languages across 25 dimensions (typing discipline, memory management, paradigm support, concurrency model, performance tier, ecosystem maturity, learning curve, primary domains, notable companies using it, killer feature, biggest weakness, year created, creator, governance model, package manager, build system, REPL availability, metaprogramming support, error handling style, null handling, generics support, FFI quality, mobile support, web support, embedded support). Use a large table, then write 200-word profiles of each language afterward.",
    "Summarize the entire plot of Shakespeare's Hamlet at twelve different lengths, in this exact order: 1 sentence, 3 sentences, 1 paragraph, 3 paragraphs, 500 words, 1,000 words, 2,000 words act-by-act, 4,000 words scene-by-scene, a 6,000-word version that includes character analysis, a 10,000-word version that includes thematic analysis and historical context, a one-page bullet outline, and a single 17-syllable haiku. Then write a 2,000-word reflection on what is preserved and what is lost at each length.",
    "Produce an alphabetized encyclopedia of every named celestial body in our solar system: all eight planets, all five officially recognized dwarf planets, all major moons (at least the top 25 by size), the largest asteroids, the most significant trans-Neptunian objects, and the most studied comets. For each entry: alphabetized header, discovery date and discoverer, etymology of name, physical properties (mass, radius, density, surface gravity, escape velocity, rotation period, orbital period, semi-major axis, eccentricity, inclination), composition, atmosphere, notable surface features, exploration history with mission list, and 200+ words of narrative description.",
    "Translate the phrase 'Hello, how are you doing today? I hope you are well' into 30 languages: French, Spanish, Italian, Portuguese (Brazilian and European, separately), German, Dutch, Swedish, Norwegian, Danish, Finnish, Polish, Russian, Ukrainian, Czech, Mandarin (simplified and traditional), Cantonese, Japanese (with kanji, hiragana, and romaji), Korean (with hangul and romanization), Vietnamese, Thai, Hindi, Bengali, Arabic (Modern Standard), Hebrew, Turkish, Swahili, Zulu, and Esperanto. For each, also provide: phonetic pronunciation guide, morphological breakdown, register notes (formal vs. casual variations), cultural notes on greeting customs, and one common response.",
    
    # Roleplay and Persona
    "Write a 6,000+ word stream-of-consciousness monologue from Leonardo da Vinci, transported to the present day, walking through a modern airport, a hospital, a smartphone repair shop, a particle physics lab, an art museum showing contemporary art, and a fast food restaurant. He should react in his own voice (thoughtful, omnivorous curiosity, polymath cross-references, occasional Tuscan exclamation), connect what he sees to his own notebooks and inventions, critique and praise, propose modifications, and have one moment of genuine awe and one of genuine sorrow. End with a letter he writes back to Ludovico Sforza.",
    "You are a senior travel concierge with 25 years of experience. Build a complete, day-by-day, hour-by-hour 14-day itinerary for a couple in their late thirties traveling through Japan in late October, with a moderate budget, interests in food/architecture/contemporary art/hiking, and a willingness to take overnight ryokan stays. Cover Tokyo, Hakone, Kyoto, Naoshima, Kanazawa, and a final return. For each day: morning/afternoon/evening blocks with specific venues, reservations needed, transit instructions with exact train lines and approximate costs, restaurant recommendations at three price tiers per meal, alternate plans for rain, etiquette notes, useful phrases, and packing reminders. Include a separate 2,000-word pre-trip preparation guide.",
    "Write a 10,000-word philosophical dialogue in the style of Plato, between five characters representing different ethical traditions (a virtue ethicist channeling Aristotle, a Kantian deontologist, a utilitarian, a contractualist, and a moral particularist), debating whether it is permissible to lie to a murderer at the door asking where their intended victim is hiding. Each character should make their strongest case, respond to the others, refine their position under pressure, and at least one should change their mind in a philosophically interesting way. Include stage directions and a final synthesis offered by a sixth character (a moral skeptic) that everyone finds unsatisfying for instructive reasons.",
    "Adopt the persona of a meticulous 1890s natural historian writing a field guide. Document twenty fictional species of magical creatures inhabiting a temperate forest. For each species: scientific binomial in faux-Latin with etymology, common names in three languages, full physical description (300+ words), habitat and range with maps described in prose, diet, mating and reproduction, social behavior, observed intelligence, magical properties with proposed mechanisms, historical encounters and folklore, conservation status, and the author's personal field notes from an encounter, complete with weather, time of day, and the author's emotional reaction. Use period-appropriate prose throughout.",
    "Assume the persona of an 18th-century ship's surgeon keeping a daily log during an 18-month voyage. Write 60 dated journal entries (averaging 400 words each) covering: departure, the first storm, an outbreak of scurvy and your treatment attempts, conflict with the captain, an encounter with another vessel, a man overboard, the crossing of the equator with its rituals, a stop at a Pacific island and your ethnographic and botanical observations, a mutiny attempt, a stretch of becalmed days where you record philosophical reflections, the eventual return, and a final entry written years later. Maintain consistent voice, evolving relationships with named crew members, and accurate period medicine.",
]
