import pytest

from modal_run import (
    art_path,
    config_tag,
    entropy_trace_source,
    find_complete_cache_T,
    null_dir,
    null_entropy_dir,
    null_trace_dir,
    uses_cached_generation_trace,
    validate_generation_record,
    wm_dir,
)


def _make_cache(root, T, prefix, indices):
    cache_dir = root / f"T{T}"
    cache_dir.mkdir(parents=True, exist_ok=True)
    for index in indices:
        (cache_dir / f"{prefix}_{index:04d}.pt").touch()


def test_returns_none_without_a_complete_cache(tmp_path):
    _make_cache(tmp_path, 2048, "null", [0, 1])

    assert find_complete_cache_T(tmp_path, 1024, 3, "null") is None


def test_selects_smallest_complete_cache_at_least_requested_length(tmp_path):
    _make_cache(tmp_path, 1024, "null", range(3))
    _make_cache(tmp_path, 2048, "null", [0, 1])
    _make_cache(tmp_path, 8192, "null", range(3))

    assert find_complete_cache_T(tmp_path, 512, 3, "null") == 1024
    assert find_complete_cache_T(tmp_path, 1500, 3, "null") == 8192
    assert find_complete_cache_T(tmp_path, 8192, 3, "null") == 8192
    assert find_complete_cache_T(tmp_path, 8193, 3, "null") is None


def test_ignores_malformed_directories_and_other_prefixes(tmp_path):
    (tmp_path / "not-a-cache").mkdir()
    (tmp_path / "Tbad").mkdir()
    _make_cache(tmp_path, 4096, "wm", range(2))
    _make_cache(tmp_path, 8192, "null", range(2))

    assert find_complete_cache_T(tmp_path, 2048, 2, "null") == 8192


def test_checks_an_exact_global_prompt_shard(tmp_path):
    _make_cache(tmp_path, 8192, "null", [125, 126, 127])

    assert find_complete_cache_T(
        tmp_path, 2048, [125, 126, 127], "null"
    ) == 8192
    assert find_complete_cache_T(
        tmp_path, 2048, [124, 125, 126], "null"
    ) is None


def test_generation_model_cache_namespaces_are_isolated():
    legacy_tag = config_tag(768, 3, 0.1, 760, 768)
    eight_b_tag = config_tag(768, 3, 0.1, 760, 768, "8B")

    assert legacy_tag == "n768_t3_eta0.10_T768_r760"
    assert eight_b_tag == (
        "n768_t3_eta0.10_T768__gen-qwen3_8b_base_r760"
    )
    assert art_path(768, 3, 0.1, 760, 768) != art_path(
        768, 3, 0.1, 760, 768, "8B"
    )
    assert wm_dir(768, 3, 0.1, 760, 768) != wm_dir(
        768, 3, 0.1, 760, 768, "8B"
    )
    assert null_dir(768) == "/data/_nulls/T768"
    assert null_dir(768, "8B") == (
        "/data/_nulls/qwen3_8b_base/T768"
    )
    assert null_entropy_dir(768, "4B", "8B") == (
        "/data/_null_entropy/qwen3_8b_base/qwen3_4b_base/T768"
    )
    assert null_trace_dir(768, "8B", "8B") == (
        "/data/_null_detection_traces/qwen3_8b_base/"
        "qwen3_8b_base/T768"
    )


def test_same_8b_model_reuses_generation_probability_trace():
    assert uses_cached_generation_trace("8B", "8B")
    assert uses_cached_generation_trace("8", "8b")
    assert not uses_cached_generation_trace("4B", "8B")
    assert entropy_trace_source("8B", "8B") == (
        "cached_generation_p_trace"
    )
    assert entropy_trace_source("4B", "8B") == "estimated_4B"


def test_8b_cache_records_require_matching_model_metadata():
    record = {
        "generation_model_size": "8B",
        "generation_model": "Qwen3-8B-Base",
    }
    validate_generation_record(record, "8B", "null", 12)
    validate_generation_record({}, "0.6B", "legacy-null", 12)

    with pytest.raises(ValueError, match="lacks generation-model metadata"):
        validate_generation_record({}, "8B", "null", 12)
    with pytest.raises(ValueError, match="generated by Qwen3-4B-Base"):
        validate_generation_record(
            {"generation_model_size": "4B"}, "8B", "null", 12
        )
    with pytest.raises(ValueError, match="generation model label"):
        validate_generation_record(
            {
                "generation_model_size": "8B",
                "generation_model": "Qwen3-4B-Base",
            },
            "8B",
            "null",
            12,
        )
